[package]
name    = "prova-prove"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "prova-prove"
path = "src/main.rs"

[dependencies]
sp1-sdk          = { workspace = true }
alloy-primitives = { workspace = true }
serde            = { workspace = true }
serde_json       = { workspace = true }
hex              = { workspace = true }
anyhow           = { workspace = true }
tokio            = { workspace = true }
reqwest          = { workspace = true }
clap             = { workspace = true }