// !/usr/bin/env node
// noir-prover/scripts/fetch_witness.js
//
// Fetches real Ethereum proof data and writes Prover.toml
// for the Noir balance_prover circuit.
//
// Usage:
//   node fetch_witness.js \
//     --rpc-url https://eth-sepolia.g.alchemy.com/v2/KEY \
//     --block 10829988 \
//     --wallet 0xefb85bcdfb03e9299a680993ab35194acb8dadda \
//     --threshold 100000000000000 \
//     --rule-id 0xb2a4a3f340d2625cecf59cb974de8cd3024a8c4786a5640cc5238fc5af98eeb7 \
//     --out ../circuit/Prover.toml

import { parseArgs } from "node:util";
import { writeFileSync } from "node:fs";
import { ethers } from "ethers";

const MAX_PROOF_NODES = 10;
const MAX_NODE_LEN    = 532;
const MAX_ACCOUNT_LEN = 110;
const MAX_HEADER_LEN  = 700;

const { values: args } = parseArgs({
  options: {
    "rpc-url":   { type: "string" },
    "block":     { type: "string" },
    "wallet":    { type: "string" },
    "threshold": { type: "string" },
    "rule-id":   { type: "string" },
    "out":       { type: "string", default: "../circuit/Prover.toml" },
  },
});

function padArray(arr, len, fill = 0) {
  const result = [...arr];
  while (result.length < len) result.push(fill);
  return result.slice(0, len);
}

function hexToBytes(hex) {
  const clean = hex.replace("0x", "");
  const padded = clean.length % 2 ? "0" + clean : clean;
  return Array.from(Buffer.from(padded, "hex"));
}

function bigintTo32Bytes(n) {
  const hex = n.toString(16).padStart(64, "0");
  return hexToBytes("0x" + hex);
}

function toNoirArray(arr) {
  return "[" + arr.map(b => `0x${b.toString(16).padStart(2,'0')}`).join(",") + "]";
}

async function main() {
  const provider = new ethers.JsonRpcProvider(args["rpc-url"]);
  const blockNum  = parseInt(args["block"]);
  const wallet    = args["wallet"];
  const threshold = BigInt(args["threshold"]);
  const ruleId    = args["rule-id"];
  const blockHex  = "0x" + blockNum.toString(16);

  console.log(`Fetching block ${blockNum}...`);
  const block = await provider.send("eth_getBlockByNumber", [blockHex, false]);
  const stateRootHex = block.stateRoot.replace("0x", "");
  const stateRoot = hexToBytes("0x" + stateRootHex);

  console.log(`State root: ${block.stateRoot}`);
  console.log(`Fetching account proof for ${wallet}...`);

  const proofResp = await provider.send("eth_getProof", [wallet, [], blockHex]);

  // Account RLP from proof
  const accountProofNodes = proofResp.accountProof.map(n => hexToBytes(n));
  const nodesBytes = accountProofNodes.map(n => padArray(n, MAX_NODE_LEN));
  const nodeLens   = accountProofNodes.map(n => n.length);

  // Pad to MAX_PROOF_NODES
  while (nodesBytes.length < MAX_PROOF_NODES) nodesBytes.push(new Array(MAX_NODE_LEN).fill(0));
  while (nodeLens.length  < MAX_PROOF_NODES)  nodeLens.push(0);

  // Build account RLP from eth_getProof fields
  // We'll use the raw RLP from the last proof node's value, but
  // for simplicity reconstruct it manually using the RLP encoder below
  const nonceHex   = proofResp.nonce.replace("0x","");
  const balanceHex = proofResp.balance.replace("0x","");
  const storageHex = proofResp.storageHash.replace("0x","");
  const codeHex    = proofResp.codeHash.replace("0x","");

  const accountRlp = encodeAccountRlp(nonceHex, balanceHex, storageHex, codeHex);
  const accountRlpPadded = padArray(accountRlp, MAX_ACCOUNT_LEN);

  console.log(`Balance: ${BigInt("0x" + (balanceHex || "0"))} wei`);
  console.log(`Threshold: ${threshold} wei`);
  console.log(`Proof nodes: ${accountProofNodes.length}`);

  // Fetch block header RLP via debug_getRawHeader
  console.log(`Fetching block header RLP...`);
  let headerRlp;
  try {
    const raw = await provider.send("debug_getRawHeader", [blockHex]);
    headerRlp = hexToBytes(raw);
  } catch (e) {
    console.error("debug_getRawHeader failed — use an Alchemy archive endpoint");
    process.exit(1);
  }
  const headerRlpPadded = padArray(headerRlp, MAX_HEADER_LEN);

  // Wallet address bytes
  const walletBytes = hexToBytes(wallet);

  // Threshold as 32 bytes big-endian
  const thresholdBytes = bigintTo32Bytes(threshold);

  // Rule ID as 32 bytes
  const ruleIdBytes = hexToBytes(ruleId);

  // Build Prover.toml
  const proofNodesStr = nodesBytes
    .map(n => toNoirArray(n))
    .join(",\n             ");

  const toml = `# Prover.toml — generated by fetch_witness.js
# Block: ${blockNum}  Wallet: ${wallet}

# ── Public inputs ─────────────────────────────────────────────────────────────
block_number   = ${blockNum}
state_root     = ${toNoirArray(stateRoot)}
wallet_address = ${toNoirArray(walletBytes)}
threshold_wei  = ${toNoirArray(thresholdBytes)}
rule_id        = ${toNoirArray(ruleIdBytes)}

# ── Private witnesses ─────────────────────────────────────────────────────────
account_rlp_len = ${accountRlp.length}
account_rlp     = ${toNoirArray(accountRlpPadded)}

num_proof_nodes = ${accountProofNodes.length}
proof_lens      = [${nodeLens.join(",")}]
proof_nodes     = [${proofNodesStr}]

header_rlp_len = ${headerRlp.length}
header_rlp     = ${toNoirArray(headerRlpPadded)}
`;

  writeFileSync(args["out"], toml);
  console.log(`\n✓ Prover.toml written to ${args["out"]}`);
  console.log(`  Run: cd ../circuit && nargo prove`);
}

// ── Minimal RLP encoder ───────────────────────────────────────────────────────

function rlpEncodeBytes(hex) {
  const padded = hex.length % 2 ? "0" + hex : hex;
  if (!padded || padded === "00") return [0x80]; // empty / zero
  const bytes = Array.from(Buffer.from(padded, "hex"));
  // Strip leading zeros for RLP integer encoding
  let start = 0;
  while (start < bytes.length - 1 && bytes[start] === 0) start++;
  const stripped = bytes.slice(start);
  if (stripped.length === 1 && stripped[0] < 0x80) return stripped;
  return [0x80 + stripped.length, ...stripped];
}

function rlpEncodeHash(hex) {
  const bytes = Array.from(Buffer.from(hex.replace("0x",""), "hex"));
  return [0xa0, ...bytes]; // 0xa0 = 0x80 + 32
}

function encodeAccountRlp(nonceHex, balanceHex, storageHex, codeHex) {
  const nonce   = rlpEncodeBytes(nonceHex   || "00");
  const balance = rlpEncodeBytes(balanceHex || "00");
  const storage = rlpEncodeHash(storageHex);
  const code    = rlpEncodeHash(codeHex);

  const payload = [...nonce, ...balance, ...storage, ...code];
  const prefix  = payload.length <= 55
    ? [0xc0 + payload.length]
    : (() => {
        const lb = encodeLengthBytes(payload.length);
        return [0xf7 + lb.length, ...lb];
      })();
  return [...prefix, ...payload];
}

function encodeLengthBytes(len) {
  const out = [];
  let n = len;
  while (n > 0) { out.unshift(n & 0xff); n >>= 8; }
  return out;
}

main().catch(e => { console.error(e); process.exit(1); });